#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
#

obj-y := timer.o reset.o clock.o
obj-y += gpio.o
obj-y += lowlevel_init.o
obj-$(CONFIG_SPL_BUILD)	+= sdram.o
obj-$(CONFIG_SPL_BUILD)	+= spl.o
